### ISSUE TITLE
Not working with iOS simulator

### ISSUE THREAD

**Issue by williamgrosset** [reisub0/hot-reload.vim#4]
Not seeing any live reload changes in the iOS simulator. Tested with `iTerm2`.

How to reproduce:
1. Add plugin to `.vimrc` and `:PlugInstall`.
2. Run `open -a Simulator`.
3. Run `flutter run`.
4. Modify and save `*.dart` file in a separate tab.

**Comment by williamgrosset** [comment]
**Update:**

Confirmed it's working with most changes inside the file 🎉

The reload that I wasn't seeing is for the function below. If I modified the `infoWindow.title`, the simulator would not pick up these changes:
```
  void _onAddMarkerButtonPressed() {
    setState(() {
      _markers.add(Marker(
        markerId: MarkerId('123'),
        position: LatLng(10, 10),
        infoWindow: InfoWindow(
          title: 'Title does not hot reload'
        ),
        icon: BitmapDescriptor.defaultMarker,
      ));
    });
  }
```

Not a huge blocker, but something I thought I'd point out if you have a workaround. Thanks for this plugin!

**Comment by autolyticus** [comment]
Hi @williamgrosset and thanks for the report!

Unfortunately I don't have a macOS device to test. Either way I don't think this is related to my plugin's functionality exactly. 

To check if my plugin is working correctly, you can check the terminal where you ran `flutter run` on and seeing if some some lines saying something like this appear every time you hit `:w` in Vim.
```
Performing hot reload...
Reloaded 1 of 448 libraries in 978ms.
```
That being said, I think I have an idea of what the issue might be:

Could you try making a small change for me and seeing if that fixes the issue:
Edit the file `<VIM_DIRECTORY>plugins/hot-reload.vim/autoload/hotReload.vim` and change the `SIGUSR1` to `SIGUSR2`? 

This makes flutter trigger a "Hot restart" instead of a "Hot reload". It does, however take a bit longer and isn't really a "hot-reload" anymore. 

IIRC you need to do a Hot restart whenever you're messing with state. Just try and see if that fixes the issue for a temporary workaround.

Also, you can check [this link](https://flutter.dev/docs/development/tools/hot-reload) for when hot-reload might not work as expected.

Cheers
